### ISSUE TITLE
Can you give us an example for how to add {{ticker::next_event::ID}} in a html template?

### ISSUE THREAD

**Issue by Samdesign90** [do-while/contao-ticker#10]
Can you give us an example for how to add {{ticker::next_event::ID}} in a HTML template? We have tried it putting in a footer section but it didn't worked.

**Comment by do-while** [comment]
If you have a event-calendar with the id of 5, then set the insert tag to {{ticker::next_event::5}}.
You get the next upcomming event in the ticker line.
The second upcomming event you get with {{ticker::event2::5}} and so on ...
