### ISSUE TITLE
Update auf Contao 5.3

### ISSUE THREAD

**Issue by Wedego** [do-while/contao-ticker#15]
satisfiable by symfony/translation-contracts[v3.4.0, v3.4.1, v3.4.2, v3.5.0].
    - Root composer.json requires do-while/contao-ticker-bundle ^1.2 -> satisfiable by do-while/contao-ticker-bundle[1.2.0, 1.2.1, 1.2.2].

**Comment by Wedego** [comment]
Danke für den Ticker, das hatte ich schon auf unserer Vereinsseite als Hingucker für Neuigkeiten.
Leider funktioniert es nicht mehr nach dem Update auf Contao 5.3
Was kann ich denn selbst machen?

**Comment by do-while** [comment]
Ich muss einfach Zeit finden, um die Kompatibilität zu Contao 5 herzustellen.

**Comment by Wedego** [comment]
Hallo Hagen, Dankeschön für deine Antwort. Wir haben uns vorerst mal mit händischem HTML und etwas Script ausgeholfen.
Ob der Verein etwas sponsoren will weis ich noch nicht.

**Comment by do-while** [comment]
Der Ticker steht jetzt in Version 2.0.0 für Contao ab 5.3 zur Verfügung

**Comment by Wedego** [comment]
Hallo Hagen,
super, vielen Dank.
Ich werde das testen und das eigene gefrickel wieder entfernen.
