### ISSUE TITLE
Nach dem Update auf Contao 4.4.4 läuft der Ticker nicht mehr

### ISSUE THREAD

**Issue by jscholtysik** [do-while/contao-ticker#3]
Nach dem Update auf Contao 4.4.4 bekomme ich zwar den Bereich angezeigt, in dem der Ticker laufen soll, die einzelnen Nachrichten werden aber nicht mehr angezeigt. 

Im Debugger vom Firefox 55.0.3 erhalte ich folgende Fehlermeldung:

> TypeError: $(...).telex is not a function[Weitere Informationen]

Die Nachrichten sind aber im Quelltext vorhanden:

`
$(document).ready(function () {
  $('#tx_1').telex({
    messages: [
                {
                  id: '1',
                  class: 'msg-white',
                  content: 'Das ist der Testticker Nr. 1, der hier an Ihnen vorbeiläuft'
                },
                {
                  id: '2',
                  class: 'msg-white',
                  content: 'Das ist der Testticker Nr. 2, der hier an Ihnen vorbeiläuft'
                },
                {
                  id: '3',
                  class: 'msg-white',
                  content: 'Das ist der Testticker Nr. 3, der hier an Ihnen vorbeiläuft'
                },
              ],
    delay: 500,
    duration: 15000,
    direction: 'normal',
    timing: 'linear',
    pauseOnHover: false  });
});
`

Dieser Scriptteil wird aber im CSS durch display:none; ausgeblendet...

Gleiches Problem auch im Google Chrome 60.0.3112.113, ist also ein generelles Problem.

**Comment by do-while** [comment]
Hallo Joachim,
bei mir läuft der Ticker auch unter 4.4.4.
Deine Fehlermeldung deutet u.U. darauf hin, dass bei Dir im Header die Zeile 
`<script src="bundles/softleisterticker/telex.min.js"></script>`
nicht (mehr) enthalten ist und dadurch das Script zum Ticker nicht geladen wird. Der Aufruf würde dann schief gehen, wie in der Fehlermeldung angedeutet.

Das mit dem display:none; ist komisch, aus meiner Erweiterung kommt das nicht, bestenfalls dynamisch aus dem Script!

**Comment by jscholtysik** [comment]
Hi Hagen,

im Header ist die Scriptzeile drin.
Ich habe gerade noch mal den Ticker über den Contao Manager deinstalliert, dann wieder installiert und noch einmal ausprobiert, gleiches Problem.
Ich kann alles einstellen für den Ticker, nur der Text wird eben nicht angezeigt.

**Comment by do-while** [comment]
Ist die Seite Online, hast Du einen Link für mich?
Und die Seite lief vorher in 4.4.3?

**Comment by jscholtysik** [comment]
Die Seite ist online, aber mit .htaccess geschützt. Ich würde Dir die Zugangsdaten dann per E-Mail schicken. An welche Adresse?

Ja, die Seite lief vorher auf 4.4.3 und der Ticker lief auch ohne Probleme. Seit 21.08.2017 wurden auch keine Änderungen mehr an der Seite gemacht.

**Comment by do-while** [comment]
info @ softleister . de

**Comment by do-while** [comment]
Ins BE komme ich leider mit den Zugangsdaten nicht.
EIgentlich sieht alles normal aus, durch den JavaScript-Fehler wird der Event nicht gesetzt und dann läuft er nicht.
Komisch ist, dass bei mir die jquery-ui.min.js vor dem telex.min.js geladen wird (wie es im template angegeben ist), bei Dir kommt es danach. Es kann sein, dass es daran liegt.

Weitere Unterschiede:
Du hast folgende JavaScripts zusätzlich:
+ mobile-menu.jquery.min.js 
+ swipe.min.js
+ jquery.flip.min.js
+ jquery-3.2.1.min.js
Vielleicht beißt sich da etwas?

**Comment by jscholtysik** [comment]
Das war ja alles vor dem 4.4.4 Update auch schon vorhanden.

**Comment by do-while** [comment]
Also es liegt an der ersten Zeile beim "Eigenen JavaScript-Code" im Seitenlayout!
Hier wird nochmal eine alte Version von JQuery geladen. Lösche ich die Zeile, läuft auch der Ticker.

Ist die Zeile denn notwendig?
`<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>`
Die überschreibt offenbar einiges aus der aktuellen Version, die zuvor vo CDN geladen wird.

 (habe alle meine Änderungen/Tests rückgängig gemacht)

**Comment by do-while** [comment]
Hallo Joachim,

nachdem ich gerade alles rückgängig gemacht habe, kommt jetzt die Fehlermeldung, 
dass der Ordner mobile-menu nicht existiert. Hast Du zu gleicher Zeit etwas verändert?

Ich kann mir nicht vorstellen, dass ich das ausgelöst habe.

Jetzt gimg es wieder????
Hast Du den Symfony-Cache gerade gelöscht?




__________________
.


Mit freundlichen Grüßen

Softleister - Contao Premium-Partner
Dipl. Ing. Hagen Klemp

Tel.:   030 - 43 60 71 22
Mobil: 0163 - 173 44 44
E-Mail: info@softleister.de

USt-IdNr. DE257903763




Mail vom Mittwoch, 6. September 2017 um 19:59:


Das war ja alles vor dem 4.4.4 Update auch schon vorhanden.

**Comment by jscholtysik** [comment]
Hallo Hagen,

auch wenn ich die Zeile
`<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>`
herausnehme, läuft der Ticker nicht.
Die Zeile ist leider notwendig, sonst läuft der Flip-Effekt unter "Unser Schule" --> "Leitung und Verwaltung" nicht mehr. Die 3.2.1 ist übrigens die neue Version von jQuery...

**Comment by jscholtysik** [comment]
Bezüglich der Fehlermeldung von mobile_menu: Ich hatte es gerade noch einmal installiert, deshalb kam wahrscheinlich auch die Fehlermeldung bei Dir.

**Comment by do-while** [comment]
ich habe es gerade noch einmal probiert, wenn ich die Zeile rausschmeiße, läuft der Ticker.
Zeile wieder drin - nix mehr

Das ist im Layout "Standard ohne Seitentitel"!




__________________
.


Mit freundlichen Grüßen

Softleister - Contao Premium-Partner
Dipl. Ing. Hagen Klemp

Tel.:   030 - 43 60 71 22
Mobil: 0163 - 173 44 44
E-Mail: info@softleister.de

USt-IdNr. DE257903763




Mail vom Mittwoch, 6. September 2017 um 20:27:


Bezüglich der Fehlermeldung von mobile_menu: Ich hatte es gerade noch einmal installiert, deshalb kam wahrscheinlich auch die Fehlermeldung bei Dir.

**Comment by jscholtysik** [comment]
Ja, das scheint es wirklich gewesen zu sein. Ich hab es auch gerade noch mal ausprobiert. Der Flip-Effekt läuft auch ohne diese Zeile sauber.

Vielen Dank! Hast ein Bier bei mir gut auf dem Camp!

**Comment by do-while** [comment]
Ich freue mich, dass es jetzt läuft.
Komisch, wenn Du auch vor 4.4.4 die gleichen Einstellungen hattest - aber egal.

Ja, Camp ist auch bald, ist gar nicht mehr so lange hin.

__________________
.


Mit freundlichen Grüßen

Softleister - Contao Premium-Partner
Dipl. Ing. Hagen Klemp

Tel.:   030 - 43 60 71 22
Mobil: 0163 - 173 44 44
E-Mail: info@softleister.de

USt-IdNr. DE257903763




Mail vom Mittwoch, 6. September 2017 um 20:46:


Ja, das scheint es wirklich gewesen zu sein. Ich hab es auch gerade noch mal ausprobiert. Der Flip-Effekt läuft auch ohne diese Zeile sauber.
Vielen Dank! Hast ein Bier bei mir gut auf dem Camp!
