### ISSUE TITLE
Ticker is neither been shown nor moving in Contao 4.7.1

### ISSUE THREAD

**Issue by Seefahrer** [do-while/contao-ticker#4]

**Comment by Seefahrer** [comment]
Unfortunately I cannot edit my former post.

**Comment by do-while** [comment]
Das Problem kann ich nachstellen, bin auf der Suche ...

**Comment by Seefahrer** [comment]
Moin Hagen,

habe mal ein wenig rumgespielt und mit der Telex v2.0 experimentiert, da die v1.0 ja wohl nicht zum Laufen zu bewegen ist. 

Ein "delay" kennt die v2 nicht mehr, "duration" wurde in "speed" umgetauft und ist nun in Pixel/Sek. anzugeben. Damit störte natürlich der von Dir definierte Minimalwert von 1000ms ein wenig. Der Ticker schiesst dann nur noch durchs Bild ... Also alle Minimalwert-Konfigurationen in Deinen configs entfernt. Zusätzlich habe ich in /templates ein modifiziertes mod_ticker.html5 abgelegt:

```
<!-- indexer::stop -->
<?php
	$GLOBALS['TL_CSS']['ticker'] = 'bundles/softleisterticker/style.css';
	$GLOBALS['TL_JAVASCRIPT']['ticker'] = 'files/freestyle-fx/js/telex.js';
?>
<section class="<?php echo $this->class; ?> block"<?php echo $this->cssID; ?><?php if ($this->style): ?> style="<?php echo $this->style; ?>"<?php endif; ?>>
	<?php if ($this->headline): ?>
		<<?php echo $this->hl; ?>><?php echo $this->headline; ?></<?php echo $this->hl; ?>>
	<?php endif; ?>
	<div id="tx_<?= $this->ticker['id'] ?>" class="tickertext"></div>
</section>
<script>
$(document).ready(function () {
	var qtx = Telex.widget('tx_<?= $this->ticker['id'] ?>',
		{
			speed: <?= $this->ticker['speed'] ?>,
			direction: '<?= $this->ticker['direction'] ?>',
			timing: '<?= $this->ticker['timing'] ?>',
			pauseOnHover: <?= $this->ticker['pauseOnHover'] ? 'true' : 'false' ?>
		},
	[ <?php foreach( $this->items as $item ): ?>
        {
			id: '<?= $item['id'] ?>',
			content: '<?= $item['content'] ?>',
			class: '<?= $item['class'] ?>'
        },
	<?php endforeach; ?> ])
});
</script>
<!-- indexer::continue -->
```

Der Ticker läuft jetzt zwar, gibt aber alle Tickertexte von allen angelegten Tickern auf einmal aus ... nicht nach Kategorie. Habe übrigens festgestellt, dass das JS in der v1.0 ebenfalls alle Tickertexte lädt, da das Script aber nicht läuft, weiß ich natürlich nicht, ob das Original-Script die Texte gefiltert nach der 'pid' ausgibt. Kann es sein, dass da etwas bei der DB Abfrage in die Hose geht?

Vielleicht hilft Dir das bei der Suche ...

"Mein" Ticker ist zu sehen unter: https://www.luetten-dieks-carlito.eu/carlito#verpaarungen

**Comment by do-while** [comment]
@Seefahrer: Danke für Deine Hilfe!
Ich habe jetzt, wie oben beschrieben, den telex 2.0 eingebunden und die Erweiterung entsprechend angepasst:
1) Probleme mit Contao 4.7 beseitigt,
2) Die Geschwindigkeit hat eine neue Skalierung,
3) Das Startdelay ist entfallen, wird von sjaakp/telex nicht mehr unterstützt

Neue Version 1.1.0
