### ISSUE TITLE
Obvious conflict with jQuery 3.3.1 in Contao 4.7.2

### ISSUE THREAD

**Issue by Seefahrer** [do-while/contao-ticker#5]
Hallo Hagen,

ich hatte heute morgen folgendes Problem im Contao-Forum berichtet:

https://community.contao.org/de/showthread.php?74463-Contao-4-7-2-Problem-mit-jQuery-in-NUR-1-Seitenlayout&p=499839&viewfull=1#post499839

Im zweiten Post habe ich erwähnt, dass die Ticker-Erweiterung die beschrieben Probleme verursacht ... habe ich getestet, sobald der Ticker als Inhaltselement oder mittels Inserttag verwendet wird, fliegt mir jQuery um die Ohren ... da gibt es wohl irgendeinen Conflict ... ?!

Hab den Ticker unter https://www.luetten-dieks-carlito.eu/#verpaarungen einstweilen aktiviert belassen, damit Du das nachvollziehen kannst ...

Das Geflackere tritt nur unter Safari auf, allerdings werfen die JS-Consolen aller Browser die Fehlermeldungen "typeerror" bzgl. "$" ...

**Comment by do-while** [comment]
Vielen Dank für die Meldung und den Pull-Request zur Lösung.
Neue Version: 1.1.1
