### ISSUE TITLE
Feature request - Nur Ticker einer bestimmten Kategorie ausgeben

### ISSUE THREAD

**Issue by Seefahrer** [do-while/contao-ticker#7]
Hallo Hagen,

ich hätte da einen "Feature Request":

Es wäre schön, wenn nur Ticker einer bestimmten Kategorie ausgegeben würden (Filter: Ticker_id).

Z.B. habe ich meine Seite https://www.luetten-dieks-carlito.eu nun zweisprachig (DE/EN) ausgelegt und würde je nach Sprache einmal den deutschen bzw. englischen Ticker ausgeben.
Z.B. Ticker_id =1 ist die deutsche, Ticker_id =2 ist die englische Version. Müßte sich doch eigentlich mit einem modifizierten select-statement relativ einfach machen lassen oder unterschätze ich das?! 

Wäre schön, wenn Du das umsetzen könntest, z.Zt. werden in beiden Sprachen die gesammelten dt. UND eng. Ticker augegeben ...

Schon einmal danke im Voraus!

**Comment by Seefahrer** [comment]
Hallo Hagen,

nichts liegt mir ferner als Dich zu" treiben", was ich wirklich nicht möchte und was bestimmt bei einer "pro Bono" Erweiterung auch nicht geht bzw. nicht erwartet wird! 

Aber vielleicht kann ich selbst zur Verwirklichung des Feature-Request beitragen. Ich habe mir einmal die "ModuleTicker.php" als auch den Code des Templates "mod_ticker.html5" angesehen...

Am Elegantesten wäre es ja wohl, in der ModuleTicker die Datenbankabfrage im "Where" so anzupassen, dass nur die Tickertexte mit einer bestimmten Ticker Category "pid" abgerufen werden. ABER wie bekomme ich in der "compile()"-Funktion Zugriff auf die Ticker-Pid für ein entsprechendes "WHERE"?

Oder man erweitert die "$arr_Items[] in der "compile()" Funktion um das Feld "pid" und filtert das Ganze im Template ... aber wie komme ich im Template an die Ticker_id des FE-Modules ...???
Hab ich mal probiert ... "dump_templatevars" zeigt mir das im FE-Modul auch entsprechend an ...

Wenn Du mir da auf die Sprünge helfen könntest, würde ich gerne meine eigenen (minimalen) Php-Kenntnisse an diesem Problem schärfen.

Wenn ich mir die Quelltexte so ansehe, habe ich das Gefühl, dass die Lösung quasi auf dem Präsentierteller vor mir liegt ... leider habe ich (noch) nicht das richtige Besteck in der Hand ...

**Comment by do-while** [comment]
Du hast es ja eilig, ich bin gerade in Urlaub.
Ich werde mich drum kümmern ...

**Comment by Seefahrer** [comment]
Uijui, im Urlaub wollte ich Dich nicht stören ... ich wünsche gute Erholung ... und Danke !!!

**Comment by Seefahrer** [comment]
Hatte "Frohe Ostern" vergessen :-)

**Comment by Seefahrer** [comment]
Du kennst doch den Unterschied zwischen Profis und Hobbyschraubern ... letztere kennen keinen Feierabend, geschweige denn Urlaub oder Feiertage ... nichts für ungut ...

**Comment by do-while** [comment]
Hallo Seefahrer,
das mit der Auswahl einzelner Kategorien im Modul war ja schon vorgesehen, hat nur nicht funktioniert.
Jetzt sollte es gehen, Du kannst jetzt mehrere Module anlegen und dort jeweils nur die passenden Kategorien auswählen.

Neue Version 1.2.0

**Comment by Seefahrer** [comment]
Danke, klappt 1a ... frohe Ostern!
