### ISSUE TITLE
IE 11 - kein Ticker

### ISSUE THREAD

**Issue by Christian50-ger** [do-while/contao-ticker#9]
hallo,
habe den Ticker 1.2.0 unter Contao 4.4.46 eingebaut.

Leider funktioniert er in IE11 nicht!
In Edge, Chrome und Firefox funktioniert er. Leider haben wir viele User die noch mit IE11 surfen.

Fehlermeldung ist:
SCRIPT438: Das Objekt unterstützt die Eigenschaft oder Methode "forEach" nicht
telex.js (5,995)

Danke für euere Hilfe

**Comment by do-while** [comment]
Laut Modulautor sjaakp/telex wird der IE >= 10 unterstützt. Dieses Script habe ich nur in die Contao-Umgebung portiert.
Auf der Originalseite gab es Bugfix-Updates, die ich jetzt übertragen habe: Version von 2.0.1 auf 2.0.4

Probiere mal bitte aus, ob es jetzt funktioniert, ich habe keinen IE11 mehr zur Verfügung (ist auch raus aus dem Support)
